/*
 * Copyright (C) 2020 Paolo Bernardi
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package cloud.bernardi.pdfjuggler;

/**
 * About dialog window.
 *
 * @author rnd
 */
public class AboutDialog extends javax.swing.JDialog {

    /**
     * Create the About dialog window.
     *
     * @param parent
     * @param modal
     */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("About " + Const.APPNAME);
        lbProgramName.setText(Const.APPNAME);
        lbVersion.setText("Version " + Const.VERSION);
        lbCopyright.setText(Const.COPYRIGHT);
        lbLicense.setText(Const.LICENSE);
        lbWebsite.setText(Const.WEBSITE);
        lbGitHub.setText(Const.GIT_HUB);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        btClose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbProgramName = new javax.swing.JLabel();
        lbVersion = new javax.swing.JLabel();
        lbCopyright = new javax.swing.JLabel();
        lbWebsite = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        lbGitHub = new javax.swing.JLabel();
        lbLicense = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 400));
        setMinimumSize(new java.awt.Dimension(700, 400));
        setPreferredSize(new java.awt.Dimension(700, 400));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cloud/bernardi/pdfjuggler/icons/icon-256.png"))); // NOI18N

        btClose.setText("Close");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        lbProgramName.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lbProgramName.setText("PDF Juggler");

        lbVersion.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lbVersion.setText("Version: x.y");

        lbCopyright.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lbCopyright.setText("Copyright");

        lbWebsite.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lbWebsite.setForeground(javax.swing.UIManager.getDefaults().getColor("textHighlight"));
        lbWebsite.setText("Website");
        lbWebsite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbWebsite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWebsiteMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel2.setText("Website:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel3.setText("GitHub:");

        lbGitHub.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lbGitHub.setForeground(javax.swing.UIManager.getDefaults().getColor("textHighlight"));
        lbGitHub.setText("GitHub");
        lbGitHub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbGitHub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbGitHubMouseClicked(evt);
            }
        });

        lbLicense.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lbLicense.setText("License");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbProgramName)
                    .addComponent(lbVersion)
                    .addComponent(lbCopyright)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbGitHub)
                            .addComponent(lbWebsite)))
                    .addComponent(lbLicense))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbProgramName)
                .addGap(18, 18, 18)
                .addComponent(lbVersion)
                .addGap(4, 4, 4)
                .addComponent(lbCopyright)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLicense)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbWebsite)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbGitHub))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btCloseActionPerformed

    private void lbWebsiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWebsiteMouseClicked
        Web.openWebsite(Const.WEBSITE);
    }//GEN-LAST:event_lbWebsiteMouseClicked

    private void lbGitHubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbGitHubMouseClicked
        Web.openWebsite(Const.GIT_HUB);
    }//GEN-LAST:event_lbGitHubMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCopyright;
    private javax.swing.JLabel lbGitHub;
    private javax.swing.JLabel lbLicense;
    private javax.swing.JLabel lbProgramName;
    private javax.swing.JLabel lbVersion;
    private javax.swing.JLabel lbWebsite;
    // End of variables declaration//GEN-END:variables
}
